version: 0.2

env:
  secrets-manager:
    PRIVATE_KEY: my-ec2-private-key  # PEM key stored in Secrets Manager

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "âœ… Installing dependencies"
      - apt-get update -y
      - apt-get install -y openssh-client zip unzip

  pre_build:
    commands:
      - echo "ðŸ” Setting up SSH key"
      - echo "$PRIVATE_KEY" > ec2-key.pem
      - chmod 400 ec2-key.pem
      - mkdir -p ~/.ssh
      - ssh-keyscan -H 18.171.56.70 >> ~/.ssh/known_hosts

  build:
    commands:
      - echo "ðŸ§ª Running tests (if any)"
      - echo "âœ… Build successful"

  post_build:
    commands:
      - echo "ðŸš€ Starting deployment to EC2"
      - scp -i ec2-key.pem -r * ubuntu@18.171.56.70:/var/www/html/
      - echo "âœ… Deployment complete"

artifacts:
  files:
    - '**/*'
